### ISSUE TITLE
Settings.php missing

### ISSUE THREAD

**Issue by dutchiexl** [megawubs/trakt-api-wrapper#1]
I woul like to use your API, but your Settings,php file is missing.

**Comment by megawubs** [comment]
Hey, what branch are you using? I haven't been developing/using the main branch for a while now, could be that something is broken there. Could you use the wrap-classes branch? This one is still in development but has a lot more functionality.

What's the error you're getting?

**Comment by dutchiexl** [comment]
Great! thanks, will get back to you later
