### ISSUE TITLE
History API call: Cannot access private property Wubs\Trakt\Request\Users\History::$username

### ISSUE THREAD

**Issue by m-vdv** [megawubs/trakt-api-wrapper#11]
$history = $trakt->users->history($username,null,null,$token)

Error: Cannot access private property Wubs\Trakt\Request\Users\History::$username

**Comment by megawubs** [comment]
Silly me. Added a feature without testing it properly. Should work-ish now. But needs proper testing.

**Comment by m-vdv** [comment]
Works!
