### ISSUE TITLE
toArray() not working on Movies

### ISSUE THREAD

**Issue by m-vdv** [megawubs/trakt-api-wrapper#12]
Error:

Attempted to call an undefined method named "toArray" of class "Wubs\Trakt\Api\Movies".

**Comment by megawubs** [comment]
What's the code that generates this error?

**Comment by m-vdv** [comment]
@megawubs 
$trakt->movies->withImages()->withFull()->summary($token,$id)->toArray();

**Comment by megawubs** [comment]
Are you sure it's `Wubs\Trakt\Api\Movies` and not `Wubs\Trakt\Media\Movie`? Because this call returns one movie object, it's automatically converted to a `Wubs\Trakt\Media\Movie` instance. So it's not a collection

**Comment by m-vdv** [comment]
After the master update it is indeed:
Error: Cannot use object of type Wubs\Trakt\Media\Movie as array

**Comment by megawubs** [comment]
@webslash Wroking on a fix for it now
