### ISSUE TITLE
Add new TV and Movie discovery API calls

### ISSUE THREAD

**Issue by m-vdv** [megawubs/trakt-api-wrapper#14]
Hi Bram

New methods have been added to help with TV show and movie discovery, please also add these to the API wrapper: 

/movies/played
/movies/watched
/movies/collected
/shows/played
/shows/watched
/shows/collected

More info: https://medium.com/@trakt/api-changelog-9f4041819718

**Comment by m-vdv** [comment]
@megawubs Any idea when you'll be able to continue working on the wrapper? :)

**Comment by megawubs** [comment]
@webslash Hey, thanks for your message. I should really finish up what I have in the pipeline. Haven't had the time and need for it lately. Will probably push something this weekend!

**Comment by megawubs** [comment]
This is added in ecdc59448d65de4d64bc3298befe2c41f5be6bed and 961f566c41a7364be530ecaa63482a3f828c8317

**Comment by m-vdv** [comment]
Thank you!!
