### ISSUE TITLE
Recommendations missing $token

### ISSUE THREAD

**Issue by m-vdv** [megawubs/trakt-api-wrapper#16]
Hi @megawubs 
The recommendation calls are missing the $token value. 
[status code] 401 [reason phrase] Unauthorized

**Comment by megawubs** [comment]
Do they don't accept the token or do you get this message even when you pass it a token? 

Op 17 sep. 2015 16:14, bij 16:14, webslash notifications@github.com schreef:

**Comment by m-vdv** [comment]
@megawubs  when I pass it a token.
OAuth is required, see docs:
http://docs.trakt.apiary.io/#reference/recommendations/movies/get-movie-recommendations

**Comment by megawubs** [comment]
strange, does the same token work on other calls with a token?

**Comment by m-vdv** [comment]
@megawubs My bad, my composer file was still pulling in the develop branch instead of master!

The fix is only present in the master branch: https://github.com/megawubs/trakt-api-wrapper/commit/704dd07c121012bd7917d610547e80dbf5c8782f 

This can be closed :+1:
