### ISSUE TITLE
Laravel 5.1 example

### ISSUE THREAD

**Issue by ghost** [megawubs/trakt-api-wrapper#18]
i followed this tutorial http://blog.wubsinfo.nl/trakt-api-wrapper/setup/oauth.html in laravel 5.1
but its not working
can you show me an example for laravel pls 

btw when i use

```
<?php
namespace App\Http\Controllers;
use Wubs\Trakt\Trakt;

class MovieController extends Controller {

    protected $trakt;

    function __construct(Trakt $trakt) {
       $this->trakt = $trakt;
    }

    public function index() {
        $trending = $this->trakt->movies->popular();
        ~r($trending); //pretty var_dump
        return view('movies.index');
   }
}
```

im getting

```
Client error response [url] https://api-v2launch.trakt.tv/movies/popular?extended=min&page=1&limit=10 [status code] 403 [reason phrase] Forbidden
```

and thats because the client_id is not defined, but how do i define it ?

**Comment by megawubs** [comment]
@DeeJaVu I've been busy updating the docks. Haven't pushed it yet as it needs it final polishing. The readme also shows how to use it with Laravel.

**Comment by ghost** [comment]
Oke thank you

**Comment by DeeJaVu** [comment]
Hello the code above is suddenly working after removing "chumper/datatable" from my vendor
this is realy strange

**Comment by SrPatinhas** [comment]
@DeeJaVu you got your code working? im getting an error in this part too :( this should have a better example how to implement. @megawubs did you got your docs updated? Thanks in advance

**Comment by ghost** [comment]
@SrPatinhas no i gave up, instead im using https://github.com/php-tmdb/laravel

**Comment by SrPatinhas** [comment]
@DeeJaVu thanks. i will try a little bit more this package ;)
