### ISSUE TITLE
Token is never send with "collected" method

### ISSUE THREAD

**Issue by snky1987** [megawubs/trakt-api-wrapper#20]
Hi,

I use your doc tutorial and try to execute this piece of code:

$provider = new TraktProvider(
    config('trakt.client_id'), config('trakt.client_secret'),config('trakt.trakt_redirect_uri')
);
$auth = new Auth($provider);
$this->trakt = new Trakt($auth);
$this->trakt->movies->page(2)->withImages()->withFull()->limit(20);

And every second request i got 403 Forbidden.
I debugged the request and $this->token is always 'null'.

When I find out the solution I will post it here in the meaning time let me know if I do anything wrong here.

(Update): Even with valid token I still have 403 every second call.

**Comment by megawubs** [comment]
Hi, 

is the code in your example the exact same code you run? Because it's missing the `->collected($token)` call. `$this->token` is probably null because it's never set.
