### ISSUE TITLE
issue with vendor:publish

### ISSUE THREAD

**Issue by zandzpider** [megawubs/trakt-api-wrapper#21]
artisan vendor:publish
Can't locate path: </mypath/vendor/wubs/trakt/src/Wubs/Trakt/Providers/Laraveltrakt.php>

**Comment by megawubs** [comment]
Can you please be a bit more descriptive? Is this the actual error message?

**Comment by ghost** [comment]
@megawubs something here is wrong https://github.com/megawubs/trakt-api-wrapper/blob/0b602d8afc682dcf4bac40a8f8dbbf5b34300c27/src/Wubs/Trakt/Providers/Laravel/TraktApiServiceProvider.php#L19

it can't locate trakt.php when you do artisan vendor:publish

i have send a pull request for a fix #22
