### ISSUE TITLE
Support for Guzzle 6

### ISSUE THREAD

**Issue by daj92109** [megawubs/trakt-api-wrapper#33]
Hello,

I see a couple of forks that have partial implementations for guzzle 6.   Do you plan to support guzzle 6 in your main package or should I work off of those forks?

**Comment by HMAZonderland** [comment]
+1 for updating to Guzzle 6.

**Comment by DHoogland** [comment]
Any updates planned?

**Comment by megawubs** [comment]
Hello, 

I have no plans or time to work on this package now or anytime soon. Please fork and change it to your likings. I'll add a notice to the readme indicating that this package is no longer maintained.
