### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by csrbrito** [megawubs/trakt-api-wrapper#6]
Without the help of an wiki its very hard to understand at first where are or how to do it.

**Comment by megawubs** [comment]
Wiki is coming, some other stuff besides this package require my attention
right now.

Op wo 8 apr. 2015 22:27 schreef csrbrito notifications@github.com:

**Comment by csrbrito** [comment]
can you reply to my email ?

**Comment by csrbrito** [comment]
i dont understand why you write that someone can contact you and help you on this and then you ignore complety! Ok, no prob i will not commit the new code i wrote to yours and complete my own version. 

Thank you anyway.

**Comment by megawubs** [comment]
You can help out, and I will respond to your message. But at the moment
other things in my life require my attention. Open Source does not have my
first priority. It's something I do in my free time, when I have the time
and energy for it. A few weeks ago I did have the time and energy, at the
moment I do not. I hope you'll understand.

Op vr 10 apr. 2015 21:59 schreef csrbrito notifications@github.com:

**Comment by rollecode** [comment]
@csrbrito Butthurt much? :wink: Open source freetime project is not an obligation or duty. Glad you have sorted things out by coding yourself, but don't unload your frustration to @megawubs, who is providing this on his free time.

I can wait as long as it needs, if not managing time to investigate this myself - then will do a proper pull request just like it is supposed to go in GitHub. We all have other things in life and it still amazes me how freetime and open source side projects are often treated as if we are at work with what we do. Just my 2 cents...

**Comment by m-vdv** [comment]
@megawubs Hi Bram

Really eager to start using this wrapper.. I'm having a hard time getting it up and running though.
Any idea when you'll have some time to continue working on it?

Better documentation or maybe even a demo project would be very useful!

Thanks for your effort.

**Comment by megawubs** [comment]
The upcoming two weeks I have to finish a project at school. After that, I'll have much more time!

**Comment by megawubs** [comment]
I've started on the documentation. It's in early stages! Please be patiant.

**Comment by m-vdv** [comment]
@megawubs Great to hear that! Your work is very much appreciated

**Comment by megawubs** [comment]
Check http://blog.wubsinfo.nl/trakt-api-wrapper/ Please, let me know if you miss anything.

**Comment by m-vdv** [comment]
Thanks @megawubs for the documentation, I'll play around with it soon. Also like the future idea for this wrapper.. looks a lot easier to use :)
